PREFIX=/usr/local/apache2
MOD_SOURCES=$(wildcard mod_*.c)
MODS=$(MOD_SOURCES:.c=.so)
SOURCES=$(filter-out $(MOD_SOURCES),$(wildcard *.c))
OBJ=$(SOURCES:.c=.o)
TARGETS=$(basename $(OBJ))
libcgi_SOURCES=$(wildcard lib/*.c)
libcgi_OBJ=$(libcgi_SOURCES:.c=.o)
CFLAGS+=-Iinclude -g
CGI_DEST=$(PREFIX)/cgi-bin
define	GITIGNOREDS
# DO NOT EDIT
# This file is auto-generated by Makefile
# Ignore object and executable files
*.o
*.obj
*.a
*.exe
*.so
*.lo
*.la
*.slo
.libs/
# Ignore specific targets
endef
export GITIGNOREDS
.PHONY:	all .gitignore clean
all:	.gitignore all-cgi all-mods
all-cgi:	libcgi.a $(TARGETS)
all-mods:	$(MODS)
$(TARGETS):	%:	%.o
$(OBJ):	$(SOURCES)
$(MODS):	%.so:	%.c
	sudo apxs -i -a -c $<
install:	install-cgi
	httpd -k restart
install-cgi:
	(for target in $(TARGETS); do \
		install -m 777 $$target $(CGI_DEST); \
	done)
.gitignore:
	echo "$$GITIGNOREDS" > $@
	(for target in $(TARGETS); do \
		echo $$target >> $@; \
	done)
lib/url.o:	lib/url.c include/cgi/url.h
lib/get.o:	lib/get.c include/cgi/get.h
libcgi.a:	$(libcgi_OBJ)
	ar rc $@ $^
readvar:	libcgi.a
viewsource:	libcgi.a
clean:
	rm -f *.o *.a *.so lib/*.o
	rm -rf .libs *.la *.lo *.slo
	rm -f $(TARGETS)
