SOURCES=$(wildcard *.c)
OBJ=$(SOURCES:.c=.o)
TARGETS=$(basename $(OBJ))
libcgi_SOURCES=$(wildcard lib/*.c)
libcgi_OBJ=$(libcgi_SOURCES:.c=.o)
CFLAGS+=-Iinclude -g
DEST=/usr/local/apache2/cgi-bin
define	GITIGNOREDS
# DO NOT EDIT
# This file is auto-generated by Makefile
# Ignore object and executable files
*.o
*.obj
*.a
*.exe
*.so
# Ignore specific targets
endef
export GITIGNOREDS
.PHONY:	all .gitignore clean
all:	.gitignore libcgi.a $(TARGETS)
$(TARGETS):	%:	%.o
$(OBJ):	$(SOURCES)
install:
	(for target in $(TARGETS); do \
		install -m 777 $$target $(DEST); \
	done)
	httpd -k restart
.gitignore:
	echo "$$GITIGNOREDS" > $@
	(for target in $(TARGETS); do \
		echo $$target >> $@; \
	done)
lib/url.o:	lib/url.c include/cgi/url.h
lib/get.o:	lib/get.c include/cgi/get.h
libcgi.a:	$(libcgi_OBJ)
	ar rc $@ $^
readvar:	libcgi.a
viewsource:	libcgi.a
clean:
	rm -f *.o *.a *.so lib/*.o
	rm -f $(TARGETS)
